name = "tokiostack"
type = "javascript"
account_id = "your-cloudflare-account-id"
workers_dev = true
route = ""
zone_id = "your-cloudflare-zone-id"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.dir = "build"

[pages]
pages_build_output_dir = "build"
